### ISSUE TITLE
TemplateNotFound when trying to install the nginx formula

### ISSUE THREAD

**Issue by cubranic** [saltstack-formulas/nginx-formula#80] opened 2015-03-25 23:09 UTC
In a CentOS 7 vagrant box, I have nginx-formula in the 'gitfs_remotes' and git in 'fileserver_backend'. But when I try to run the `nginx` state, I get the following error:

```
$ sudo salt-call state.sls nginx
[INFO    ] pygit2 gitfs_provider enabled
[INFO    ] Wrote new gitfs_remote map to /var/cache/salt/minion/gitfs/remote_map.txt
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file from saltenv 'base', ** done ** u'nginx/init.sls'
[INFO    ] Fetching file from saltenv 'base', ** done ** 'nginx/map.jinja'
[CRITICAL] Rendering SLS 'base:nginx' failed: Jinja error: nginx/map.jinja
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 286, in render_jinja_tmpl
    output = template.render(**unicode_context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python2.7/site-packages/salt/utils/jinja.py", line 132, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: nginx/map.jinja

; line 1

---
{% from "nginx/map.jinja" import nginx as nginx_map with context %}    <======================

include:
  - nginx.common
{% if salt['pillar.get']('nginx:use_upstart', nginx_map['use_upstart']) %}
  - nginx.upstart
[...]

---
```

**Comment by gravyboat** [comment] 2015-03-26 02:14
@cubranic Did you set the remote as the main nginx repo and not the subdirectory (https://github.com/saltstack-formulas/nginx-formula/tree/master/nginx)? That's the only thing that I can think would cause this since it hasn't been updated since October. In addition you should probably fork the repo and use gitfs from there so you don't get changes that you don't want.

**Comment by cubranic** [comment] 2015-03-26 02:39
> @cubranic Did you set the remote as the main nginx repo and not the subdirectory (https://github.com/saltstack-formulas/nginx-formula/tree/master/nginx)?

Yes, I have the main repo as the remote:
```
$ cat /etc/salt/minion
file_client: local

fileserver_backend:
  - roots
  - git

gitfs_remotes:
  - https://github.com/saltstack-formulas/epel-formula.git
  - https://github.com/saltstack-formulas/nginx-formula.git
```

**Comment by gravyboat** [comment] 2015-03-26 03:06
Confirmed I'm getting the same thing on a fresh droplet over at digital ocean with a centos7 image.

**Comment by gravyboat** [comment] 2015-03-26 03:17
@cubranic I've confirmed that this works fine if you have it checked out locally and have the nginx directory under /srv/salt. Not quite sure what is causing this remote issue. Unfortunately I don't have time to troubleshoot it tonight.

**Comment by noelmcloughlin** [comment] 2019-01-26 12:04
Closing since nobody has replicated issue.

**Closed by noelmcloughlin** 2019-01-26 12:04 UTC
